import { Planta } from '../plantas/plantas.model';

export const PLANTAS: Planta[] =
    [
        {
            "id": 1,
            "nome": "Yacon",
            "nomec": "Smallanthus sonchifolius",
            "descricao": "O yacon, também conhecido como batata-yacon, é uma planta cujas raízes tuberosas são consumidas normalmente cruas ou na forma de suco. As raízes tuberosas do yacon são ricas em inulina (polissacarídeos de frutose), o que lhes proporciona um sabor adocicado. As folhas e as pontas dos ramos podem ser consumidas cozidas. Também é uma planta usada para fins medicinais, especialmente por suas folhas apresentarem propriedades anti-hiperglicêmicas.",
            "tipo": "",
            "luz": "Luz solar direta ou sombra parcial",
            "temperatura": "10°C a 26°C",
            "epoca": "Primavera",
            "tempo": "6 a 12 meses",
            "solo": "Bem drenado, profundo, sem pedras e detritos, fértil e rico em matéria orgânica.pH de 6 a 7,5.",
            "irrigacao": "Manter o solo sempre úmido, sem ficar encharcado",
            "pestes": "",
            "propagacao": "",
            "imagem": "yacon"
        },
        {
            "id": 2,
            "nome": "Wasabi",
            "nomec": "Eutrema japonicum",
            "descricao": "A wasabi, também conhecida como wasabia e raiz-forte-japonesa, é uma planta nativa do Japão, cultivada principalmente para uso de seu espesso caule subterrâneo (rizoma), mas que é frequentemente chamado incorretamente de raiz. Quando ralado, seu rizoma apresenta um sabor bastante picante, similar ao da raiz-forte, mas não idêntico. Suas folhas também podem ser consumidas e têm um sabor menos picante do que o rizoma.",
            "tipo": "",
            "luz": "Sombra parcial",
            "temperatura": "8°C a 20°C",
            "epoca": "Ano todo",
            "tempo": "18 a 24 meses",
            "solo": "solo úmido. pH entre 6 e 7.",
            "irrigacao": "Manter o solo sempre úmido, sem ficar encharcado",
            "pestes": "",
            "propagacao": "",
            "imagem": "wasabi"
        },
        {
            "id": 3,
            "nome": "Vinagreira",
            "nomec": "Hibiscus sabdariffa",
            "descricao": "A vinagreira, também conhecida como rosela e quiabo-azedo entre outros nomes, é um arbusto vigoroso que pode chegar a atingir quase 5 m de altura em plantas cujos ramos são utilizados para a extração de fibras têxteis. As variedades cultivadas que são utilizadas como alimento são menores, atingindo até 2,5 m de altura. Destas podem ser consumidas como verdura as folhas jovens e as pontas dos ramos, cruas, refogadas ou cozidas. As folhas, dependendo da cultivar, podem ser verdes ou avermelhadas. Os caules e pecíolos (os talos das folhas) geralmente são vermelhos. Os cálices das flores são vermelhos e carnudos, sendo utilizados no feitio de refrescos, chás, geleias e doces. Tanto as folhas quando os cálices têm um agradável sabor ácido, vindo daí seu nome popular vinagreira. As flores (a corola da flor) e as sementes também podem ser consumidas, mas os cálices são mais apreciados e sua colheita impossibilita a colheita da corola da flor ou de suas sementes.",
            "tipo": "",
            "luz": "Luz solar direta",
            "temperatura": "Quente e úmido",
            "epoca": "Setembro a Abril",
            "tempo": "60 a 90 dias",
            "solo": "Bem drenado, profundos, férteis e ricos em matéria orgânica.",
            "irrigacao": "Manter o solo sempre úmido, sem ficar encharcado",
            "pestes": "",
            "propagacao": "",
            "imagem": "vinagreira"
        },
        {
            "id": 4,
            "nome": "Tupinambo",
            "nomec": "Helianthus tuberosus",
            "descricao": "O tupinambo, também chamado de girassol-batateiro, é uma planta domesmo gênero do girassol. Nativo do leste da América do Norte, já era cultivado pelos povos nativos da região antes da chegada dos europeus. Seus tubérculos são ricos em inulina, um polissacarídeo da frutose, o que lhes proporciona um leve sabor adocicado. São normalmente consumidos cozidos, mas podem ser consumidos crus em saladas se cortados em fatias finas.",
            "tipo": "",
            "luz": "Luz solar direta.",
            "temperatura": "10°C a 26°C",
            "epoca": "Primavera",
            "tempo": "6 a 10 meses",
            "solo": "Bem drenado, bem drenado, leve, sem pedras e outros detritos, fértil e rico em matéria orgânica",
            "irrigacao": "Manter o solo sempre úmido, sem ficar encharcado",
            "pestes": "",
            "propagacao": "",
            "imagem": "tupinambo"
        },
        {
            "id": 5,
            "nome": "Repolho",
            "nomec": "Brassica olerace",
            "descricao": "É uma planta bienal que forma uma espécie de roseta de folhas durante o primeiro ano de cultivo; as folhas dessa variedade são sempre carnudas e possuem proteínas capazes de fazê-las armazenar água e nutrientes. No segundo ano, as reservas de nutrientes formam uma inflorescência amarela de um a dois metros de altura.",
            "tipo": "Erva",
            "luz": "Luz solar direta",
            "temperatura": "10°C a 26°C",
            "epoca": "Ano todo",
            "tempo": "75 a 88 dias",
            "solo": " Argila e areia com boa drenagem e fertilizante básico",
            "irrigacao": "Regar regularmente, sem acúmulo de água",
            "pestes": "Míldio, podridão macia, pulgões, lagartas de repolho",
            "propagacao": "Plântula",
            "imagem": "repolho"
        },
        {
            "id": 6,
            "nome": "Beterraba",
            "nomec": "Beta vulgaris",
            "descricao": "É uma planta herbácea anual ou perene, glabra ou hirsuta, ereta ou decumbente e com até 2m de altura. É ramificado e frondoso, de cor verde e violeta e possui raízes finas ou tuberosas ricas em açúcar.",
            "tipo": "Erva",
            "luz": "Luz solar direta",
            "temperatura": "20°C a 30°C",
            "epoca": "Verão",
            "tempo": "60 a 70 dias",
            "solo": " Argila e areia com boa drenagem e fertilizante a cada 16 dias",
            "irrigacao": "Regar regularmente, sem acúmulo de água",
            "pestes": "-",
            "propagacao": "Semeadura",
            "imagem": "beterraba"
        },
        {
            "id": 7,
            "nome": "Cenoura",
            "nomec": "Daucus carota",
            "descricao": "É uma planta bienal que forma uma roseta de folhas na primavera e no verão, enquanto desenvolve a raiz napiforme espessa, que armazenará grandes quantidades de açúcar para a floração do ano seguinte. O caule da flor cresce cerca de 10 cm com um umbel de flores brancas no ápice.",
            "tipo": "Erva",
            "luz": "Luz solar direta",
            "temperatura": "20°C a 30°C",
            "epoca": "Primavera até Outono",
            "tempo": "120 dias",
            "solo": " Areia, giz e solo argiloso, com boa drenagem e fertilizante de 2 a 3 vezes durante o crescimento",
            "irrigacao": "Tolerante à seca, menos rega, água quando o solo está seco",
            "pestes": "Oídio, podridão das raízes, doenças esclerotina, mosca raiz de cenoura e pulgões",
            "propagacao": "Semeadura",
            "imagem": "cenoura"
        },
        {
            "id": 8,
            "nome": "Batata-Doce",
            "nomec": "Ipomoea batatas",
            "descricao": "São plantas de escalada perenes; com hastes prostradas ou volúveis, um tanto suculentas, mas também finas e herbáceas, geralmente com raízes nos nós, glabras ou pubescentes. Folhas variáveis, inteiras ou dentadas até 5-7 lobadas, cordadas a ovar, com 5 a 10 cm de comprimento e largura, glabras ou pubescentes.",
            "tipo": "Erva",
            "luz": "Luz solar direta",
            "temperatura": "20°C a 30°C",
            "epoca": "Primavera e Verão",
            "tempo": "120 a 150 dias",
            "solo": "Areia e argila, com fertilização durante o crescimento",
            "irrigacao": "Mantenha úmido, mas sem acúmulo de água",
            "pestes": "Oídio, infecção viral, moscas brancas, ácaros vermelhos",
            "propagacao": "Estacas",
            "imagem": "batata-doce"
        },
        {
            "id": 9,
            "nome": "Nabo",
            "nomec": "Brassica rapa",
            "descricao": "É uma planta amplamente cultivada e que produz oleaginosas. O óleo de canola é produzido a partir do nabo oleaginoso. Nabo atrai borboletas brancas que ganham nutrientes de suas flores.",
            "tipo": "Erva",
            "luz": "Luz solar direta ou sombra parcial",
            "temperatura": "20°C a 30°C",
            "epoca": "Verão",
            "tempo": "80 a 120 dias",
            "solo": "Areia e argila, com fertilização básica",
            "irrigacao": "Regar regularmente, sem acúmulo de água",
            "pestes": "Mídio, podridão macia, pulgões, lagartas de repolho",
            "propagacao": "Semeadura",
            "imagem": "nabo"
        },
        {
            "id": 10,
            "nome": "Cebola",
            "nomec": "Allium cepa",
            "descricao": "Em relação à sua morfologia, a cebola possui um sistema radicular composto por inúmeras raízes rasas, esbranquiçadas e fasciculadas, que emergem de uma haste como um disco. Este disco-tronco possui numerosos nós e entrenós muitos cursos e, a partir disso, as folhas saem.",
            "tipo": "Erva",
            "luz": "Luz solar direta",
            "temperatura": "10°C a 25°C",
            "epoca": "Inverno",
            "tempo": "85 a 300 dias",
            "solo": "Areia e argila, com fertilização regular",
            "irrigacao": "Regar regularmente, sem acúmulo de água",
            "pestes": "Podridão branca, ferrugem, míldio doença de ponta branca, mosca de cebola, mariposa de alho poró",
            "propagacao": "Semeadura",
            "imagem": "cebola"
        },
        {
            "id": 11,
            "nome": "Ervilha Aspargo",
            "nomec": "Lotus tetragonolobus",
            "descricao": "A planta possui um sistema vegetativo pouco desenvolvido, embora com uma raiz articulada que tende a ser profunda o suficiente. As folhas são compostas por pares de folhetos que terminam em gavinhas.As inflorescências estão agrupadas em grandes brácteas foliáceas que são inseridas nas flores.",
            "tipo": "Erva, videira",
            "luz": "Luz solar direta",
            "temperatura": "20°C a 30°C",
            "epoca": "Primavera e Verão",
            "tempo": "85 dias",
            "solo": "Areia e argila, com fertilização uma vez por semana durante a floração",
            "irrigacao": "Regar regularmente, sem acúmulo de água",
            "pestes": "-",
            "propagacao": "Semeadura e estacas",
            "imagem": "ervilha-aspargo"
        },
        {
            "id": 12,
            "nome": "Agrião da Terra",
            "nomec": "Barbarea verna",
            "descricao": "O agrião-da-terra, também chamado de erva-de-santa-bárbara, é uma pequena planta cujas folhas lembram em forma e sabor as folhas do agrião-da-água. Quando floresce, esta planta atinge de 30 a 90 cm de altura, mas durante seu período útil de cultivo geralmente não ultrapassa os 15 cm de altura. Suas folhas têm um agradável sabor e podem ser consumidas cruas em saladas e sanduiches, ou podem ser utilizadas em sopas e outras receitas culinárias",
            "tipo": "Erva",
            "luz": "Luz solar direta ou sombra parcial",
            "temperatura": "20°C a 30°C",
            "epoca": "Primavera, Verão e Outono",
            "tempo": "85 dias",
            "solo": "Areia e argila, com fertilização uma vez por semana durante a floração",
            "irrigacao": "Regar regularmente, sem acúmulo de água",
            "pestes": "Podridão branca, ferrugem, míldio doença de ponta branca, mosca de cebola, mariposa de alho poró",
            "propagacao": "Semeadura, estacas",
            "imagem": "agriao-da-terra"
        }
    ]
/* Caso o tipo de algum item mude, seja adicionado ou seja excluido, fazer a mesma alteração no arquivo de interface de planta */